import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export const metadata: Metadata = {
  title: "Cipher-21 Web Portal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`bg-black text-[#149414]`}
      >
        <Navbar />
        <main className="pt-16"> {/* Adjust padding to match navbar height */}
          {children}
          <Footer />
        </main>
        <Toaster />
      </body>
    </html>
  );
}
